/*
 * Rosalie's Mupen GUI - https://github.com/Rosalie241/RMG
 *  Copyright (C) 2020-2025 Rosalie Wanders <rosalie@mailbox.org>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License version 3.
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
#ifndef RMGK_SCRIPT_MANAGER_HPP
#define RMGK_SCRIPT_MANAGER_HPP

#include <memory>
#include <string>
#include <vector>
#include <cstdint>
#include <functional>
#include <unordered_map>

class ScriptEngine;

// Global script manager — owns one ScriptEngine per loaded script file.
// Only one instance of each script (by filepath) may run at a time.
class ScriptManager {
public:
    static ScriptManager& GetInstance();

    // Load and start a script. Returns false if already running or load failed.
    bool LoadScript(const std::string& filepath);

    // Stop a specific script (by filepath). Returns false if not running.
    bool StopScript(const std::string& filepath);

    // Stop all running scripts.
    void StopAll();

    // Returns filepaths of all currently running scripts.
    std::vector<std::string> GetRunningScripts() const;

    // Returns whether a script is currently running.
    bool IsScriptRunning(const std::string& filepath) const;

    // Receive output generated by any script.
    void SetOutputCallback(std::function<void(const std::string&)> callback);

    // Deliver a user-typed input line to all running scripts.
    void SubmitInput(const std::string& text);

    // Set a blocking callback used by emu.input() to prompt the user for a string.
    void SetInputPromptCallback(std::function<std::string(const std::string&)> callback);

    // Called each frame from emulation.
    void OnFrameUpdate(uint32_t pc = 0);

    // Called per instruction (via PCCallback) — fires PC hooks.
    void OnPCUpdate(uint32_t pc);

    // Called when emulation stops — shuts down all engines.
    void OnEmulationStop();

    void OnEmulationPause();
    void OnEmulationResume();

private:
    ScriptManager() = default;
    ~ScriptManager() = default;

    ScriptManager(const ScriptManager&) = delete;
    ScriptManager& operator=(const ScriptManager&) = delete;

    // filepath → engine
    std::unordered_map<std::string, std::unique_ptr<ScriptEngine>> m_engines;
    std::function<void(const std::string&)>         m_outputCallback;
    std::function<std::string(const std::string&)>  m_inputPromptCallback;
};

#endif // RMGK_SCRIPT_MANAGER_HPP
